spring:
  datasource:
    druid:
      username: root
      password: 12345
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/liuyu?useUnicode=true&characterEncoding=UTF-8
      # rewriteBatchedStatements=true 开启批处理
      #初始化时建立物理连接的个数
      initial-size: 4
      #最大连接池数量
      max-active: 8
      #最小连接池数量
      min-idle: 4
      #用来检测连接是否有效的sql
      validation-query: select 1 from dual;
      #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
      test-on-borrow: false
      #建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测
      #如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      #有两个含义：1) Destroy线程会检测连接的间隔时间2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 10000
      #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降
      #如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 5000
      use-unfair-lock: true
      query-timeout: 5000
      #要求程序从池中get到连接后, N 秒后必须close,否则druid 会强制回收
      remove-abandoned: true
      remove-abandoned-timeout: 60
      web-stat-filter:
        enabled: true
      stat-view-servlet:
        enabled: true
        login-username: liuyu
        login-password: 12345
      filter:
        stat:
          enabled: true
          merge-sql: true
          slow-sql-millis: 5000
          log-slow-sql: true
#        slf4j:
#          enabled: true
#          result-set-log-enabled: true
#          connection-log-enabled: true
#          data-source-log-enabled: true
#          statement-log-enabled: true
#          statement-executable-sql-log-enable: true


logging:
  config: classpath:config/logback-spring-prod.xml