spring:
  application:
    name: template
  profiles:
    active: dev

server:
  port: 8080
logging:
  path: log
app:
  async:
    corePoolSize: 4
    maxPoolSize: 8
    queueCapacity: 2000
    keepLiveSeconds: 10
  schedule:
    corePoolSize: 2
